function mdl_name = build_full_car_model()
% BUILD_FULL_CAR_MODEL Programmatically builds and saves abs_full_car.slx
% 4-wheel vehicle ABS simulation model with pitch dynamics and split-mu yaw handling.

mdl_name = 'abs_full_car';
save_path = fullfile(fileparts(mfilename('fullpath')), [mdl_name, '.slx']);

if bdIsLoaded(mdl_name)
    close_system(mdl_name, 0);
end

new_system(mdl_name);
open_system(mdl_name);

set_param(mdl_name, 'SolverType', 'Fixed-step');
set_param(mdl_name, 'Solver', 'ode4');
set_param(mdl_name, 'FixedStep', '0.0005');
set_param(mdl_name, 'StopTime', '6.0');

% Add Driver Source
add_block('simulink/Sources/Step', [mdl_name, '/Driver_Pedal'], ...
    'Position', [50, 100, 90, 140], ...
    'Time', '0.10', ...
    'Before', '0.0', ...
    'After', '15.0e6');

% Full Car Core Block
mf_block = [mdl_name, '/FullCar_ABS_Core'];
add_block('simulink/User-Defined Functions/MATLAB Function', mf_block, ...
    'Position', [160, 60, 520, 240]);

rt = sfroot;
m = rt.find('-isa', 'Stateflow.Machine', 'Name', mdl_name);
chart = m.find('-isa', 'Stateflow.EMChart', 'Path', mf_block);

script_code = sprintf([ ...
    'function [v_kmh, yaw_deg, yaw_rate_dps, dist_m, Fz_F_kN, Fz_R_kN] = FullCar_ABS_Core(P_driver, ctrl_mode, is_split_mu)\n', ...
    '%% Full Vehicle 4-Wheel ABS Simulation Block\n', ...
    'persistent v w x ax psi psi_dot P_act ctrl_phase P_hold w_prev\n', ...
    'if isempty(v)\n', ...
    '    v = 100 / 3.6;\n', ...
    '    w = (v / 0.32) * ones(4, 1);\n', ...
    '    x = 0.0;\n', ...
    '    ax = 0.0;\n', ...
    '    psi = 0.0;\n', ...
    '    psi_dot = 0.0;\n', ...
    '    P_act = zeros(4, 1);\n', ...
    '    ctrl_phase = zeros(4, 1);\n', ...
    '    P_hold = zeros(4, 1);\n', ...
    '    w_prev = w;\n', ...
    'end\n\n', ...
    'dt = 0.0005;\n', ...
    'm  = 1600.0;\n', ...
    'Jw = 1.20;\n', ...
    'R  = 0.32;\n', ...
    'L  = 2.60; a = 1.15; b = 1.45;\n', ...
    'h  = 0.50; d = 1.55; Iz = 2400.0;\n', ...
    'Kb = 1.8e-4;\n\n', ...
    '%% Dynamic Pitch Load Transfer\n', ...
    'Fz_F_total = max(500.0, (m * 9.81 * b - m * ax * h) / L);\n', ...
    'Fz_R_total = max(500.0, (m * 9.81 * a + m * ax * h) / L);\n', ...
    'Fz = [Fz_F_total/2; Fz_F_total/2; Fz_R_total/2; Fz_R_total/2];\n\n', ...
    '%% Wheel kinematics\n', ...
    'vw = w * R;\n', ...
    'slip = (v - vw) ./ max(v, 0.1);\n', ...
    'slip = max(0.0, min(1.0, slip));\n\n', ...
    'aw = ((w - w_prev) / dt) * R;\n', ...
    'w_prev = w;\n\n', ...
    '%% Brake command per wheel\n', ...
    'P_cmd = zeros(4, 1);\n', ...
    'for i = 1:4\n', ...
    '    if ctrl_mode == 0 || v < 1.5\n', ...
    '        P_cmd(i) = P_driver;\n', ...
    '    else\n', ...
    '        %% Bosch 3-Phase Logic\n', ...
    '        is_locking = (slip(i) > 0.19) || (slip(i) > 0.09 && aw(i) < -25.0);\n', ...
    '        if ctrl_phase(i) == 0 && is_locking\n', ...
    '            ctrl_phase(i) = 2; P_hold(i) = 0.78 * P_act(i);\n', ...
    '        elseif ctrl_phase(i) == 2 && (aw(i) > 3.0 || (slip(i) < 0.15 && aw(i) > 0))\n', ...
    '            ctrl_phase(i) = 1;\n', ...
    '        elseif ctrl_phase(i) == 1 && (aw(i) < 1.5 && slip(i) < 0.14)\n', ...
    '            ctrl_phase(i) = 0;\n', ...
    '        end\n', ...
    '        if ctrl_phase(i) == 2\n', ...
    '            P_cmd(i) = max(0.72 * P_hold(i), P_act(i) - 9.0e7 * dt);\n', ...
    '        elseif ctrl_phase(i) == 1\n', ...
    '            P_cmd(i) = P_hold(i);\n', ...
    '        else\n', ...
    '            P_cmd(i) = min(P_driver, P_act(i) + 8.5e7 * dt);\n', ...
    '        end\n', ...
    '    end\n', ...
    'end\n\n', ...
    '%% Select-Low Yaw Control for split-mu\n', ...
    'if is_split_mu > 0 && ctrl_mode > 0\n', ...
    '    P_cmd(3) = min(P_cmd(3), P_cmd(4));\n', ...
    '    P_cmd(4) = P_cmd(3);\n', ...
    '    if abs(P_cmd(1) - P_cmd(2)) > 3.5e6\n', ...
    '        if P_cmd(1) > P_cmd(2)\n', ...
    '            P_cmd(1) = P_cmd(2) + 3.5e6;\n', ...
    '        else\n', ...
    '            P_cmd(2) = P_cmd(1) + 3.5e6;\n', ...
    '        end\n', ...
    '    end\n', ...
    'end\n\n', ...
    '%% Hydraulic Actuator Dynamics\n', ...
    'for i = 1:4\n', ...
    '    dP = (P_cmd(i) - P_act(i)) / 0.025;\n', ...
    '    dP = max(-1.2e8, min(8.0e7, dP));\n', ...
    '    P_act(i) = max(0.0, min(15.0e6, P_act(i) + dP * dt));\n', ...
    'end\n', ...
    'Tb = Kb * P_act;\n\n', ...
    '%% Tire Friction (Split-mu: Left = Dry, Right = Ice)\n', ...
    'Fx = zeros(4, 1);\n', ...
    'for i = 1:4\n', ...
    '    if is_split_mu > 0 && (i == 2 || i == 4)\n', ...
    '        B=20.0; C=1.45; D=0.15; E=0.10; %% Ice on right wheels\n', ...
    '    else\n', ...
    '        B=10.0; C=1.60; D=1.00; E=0.40; %% Dry asphalt\n', ...
    '    end\n', ...
    '    arg = B*slip(i) - E*(B*slip(i) - atan(B*slip(i)));\n', ...
    '    mu = max(0.0, D * sin(C * atan(arg)));\n', ...
    '    Fx(i) = mu * Fz(i);\n', ...
    'end\n\n', ...
    '%% Yaw Dynamics & Stopping\n', ...
    'Mz = ((Fx(1) + Fx(3)) - (Fx(2) + Fx(4))) * (d / 2);\n', ...
    'if v > 0.5\n', ...
    '    ax = -sum(Fx) / m;\n', ...
    '    v  = max(0.0, v + ax * dt);\n', ...
    '    x  = x + v * dt;\n', ...
    '    psi_dot = psi_dot + (Mz / Iz) * dt;\n', ...
    '    psi = psi + psi_dot * dt;\n', ...
    '    for i = 1:4\n', ...
    '        dw = (-Tb(i) + Fx(i) * R) / Jw;\n', ...
    '        w(i) = max(0.0, w(i) + dw * dt);\n', ...
    '    end\n', ...
    'else\n', ...
    '    v = 0.0; w(:) = 0.0; ax = 0.0; psi_dot = 0.0;\n', ...
    'end\n\n', ...
    'v_kmh         = v * 3.6;\n', ...
    'yaw_deg       = psi * (180 / pi);\n', ...
    'yaw_rate_dps  = psi_dot * (180 / pi);\n', ...
    'dist_m        = x;\n', ...
    'Fz_F_kN       = Fz_F_total * 1e-3;\n', ...
    'Fz_R_kN       = Fz_R_total * 1e-3;\n' ...
]);

chart.Script = script_code;

% Constant inputs
add_block('simulink/Sources/Constant', [mdl_name, '/Ctrl_Mode'], ...
    'Position', [50, 160, 90, 180], 'Value', '1');
add_block('simulink/Sources/Constant', [mdl_name, '/Is_Split_Mu'], ...
    'Position', [50, 200, 90, 220], 'Value', '1');

% Sinks
add_block('simulink/Sinks/To Workspace', [mdl_name, '/v_kmh_out'], ...
    'Position', [580, 60, 640, 80], 'VariableName', 'v_kmh', 'SaveFormat', 'Array');
add_block('simulink/Sinks/To Workspace', [mdl_name, '/yaw_deg_out'], ...
    'Position', [580, 90, 640, 110], 'VariableName', 'yaw_deg', 'SaveFormat', 'Array');
add_block('simulink/Sinks/To Workspace', [mdl_name, '/yaw_rate_out'], ...
    'Position', [580, 120, 640, 140], 'VariableName', 'yaw_rate', 'SaveFormat', 'Array');
add_block('simulink/Sinks/To Workspace', [mdl_name, '/dist_m_out'], ...
    'Position', [580, 150, 640, 170], 'VariableName', 'dist_m', 'SaveFormat', 'Array');

% Lines
add_line(mdl_name, 'Driver_Pedal/1', 'FullCar_ABS_Core/1');
add_line(mdl_name, 'Ctrl_Mode/1',    'FullCar_ABS_Core/2');
add_line(mdl_name, 'Is_Split_Mu/1',  'FullCar_ABS_Core/3');

add_line(mdl_name, 'FullCar_ABS_Core/1', 'v_kmh_out/1');
add_line(mdl_name, 'FullCar_ABS_Core/2', 'yaw_deg_out/1');
add_line(mdl_name, 'FullCar_ABS_Core/3', 'yaw_rate_out/1');
add_line(mdl_name, 'FullCar_ABS_Core/4', 'dist_m_out/1');

save_system(mdl_name, save_path);
close_system(mdl_name);
fprintf('Successfully generated and saved Simulink model: %s\n', save_path);

end
